module.exports = [
    "Johann Sebastian Bach",
    "Wolfgang Amadeus Mozart",
    "Ludwig van Beethoven",
    "Pyotr Ilyich Tchaikovsky",
    "Richard Wagner",
    "Johannes Brahms",
    "Franz Schubert",
    "Robert Schumann",
    "Giuseppe Verdi",
    "George Frideric Handel",
    "Franz Joseph Haydn",
    "Antonio Vivaldi",
    "Igor Stravinsky",
    "Frederic Chopin",
    "Felix Mendelssohn",
    "Claude Debussy",
    "Franz Liszt",
    "Sergei Rachmaninov",
    "Antonin Dvorak",
    "Gustav Mahler"
];